2025-09-04 00:05:58|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2025-09-04 01:06:52|INFO    |root                            |BAZARR Running cache maintenance|
2025-09-04 04:00:00|INFO    |root                            |BAZARR All existing episode subtitles indexed from disk.|
2025-09-04 04:00:00|INFO    |root                            |BAZARR All existing movie subtitles indexed from disk.|
2025-09-04 04:06:18|INFO    |root                            |BAZARR Finished searching for Subtitles to upgrade. Check History for more information.|
2025-09-04 05:38:42|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
2025-09-04 06:05:58|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2025-09-04 11:38:42|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
2025-09-04 12:05:58|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2025-09-04 15:01:59|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
2025-09-04 15:02:13|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-09-04 15:33:15|INFO    |root                            |Scheduler will use this timezone: Asia/Jerusalem|
2025-09-04 15:33:18|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-09-04 15:33:18|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-09-04 15:33:18|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-09-04 15:33:18|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://[::]:6767|
2025-09-04 15:47:41|INFO    |root                            |Scheduler will use this timezone: Asia/Jerusalem|
2025-09-04 15:47:43|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-09-04 15:47:43|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-09-04 15:47:43|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-09-04 15:47:43|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://[::]:6767|
2025-09-04 15:47:48|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-09-04 15:48:03|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-09-04 15:51:14|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
2025-09-04 15:51:14|ERROR   |root                            |BAZARR SignalR client for Sonarr connection as been lost. Trying to reconnect...|
2025-09-04 15:54:33|INFO    |root                            |Scheduler will use this timezone: Asia/Jerusalem|
2025-09-04 15:54:34|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-09-04 15:54:34|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-09-04 15:54:34|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-09-04 15:54:34|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://[::]:6767|
2025-09-04 15:54:34|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-09-04 15:54:39|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-09-04 16:07:37|ERROR   |root                            |BAZARR SignalR client for Sonarr connection as been lost. Trying to reconnect...|
2025-09-04 16:07:37|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
2025-09-04 16:41:53|INFO    |root                            |Scheduler will use this timezone: Asia/Jerusalem|
2025-09-04 16:42:00|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-09-04 16:42:00|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-09-04 16:42:00|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-09-04 16:42:00|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://[::]:6767|
2025-09-04 16:42:00|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-09-04 16:42:00|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-09-04 13:58:52|INFO    |root                            |Scheduler will use this timezone: Etc/UTC|
2025-09-04 13:58:53|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-09-04 13:58:53|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-09-04 13:58:53|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-09-04 13:58:53|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://[::]:6767|
2025-09-04 13:58:53|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-09-04 13:58:53|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-09-04 13:59:03|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
2025-09-04 13:59:15|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-09-04 14:52:10|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
2025-09-04 14:52:10|ERROR   |root                            |BAZARR SignalR client for Sonarr connection as been lost. Trying to reconnect...|
2025-09-04 14:58:31|INFO    |root                            |Scheduler will use this timezone: Etc/UTC|
2025-09-04 14:58:35|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-09-04 14:58:35|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-09-04 14:58:35|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-09-04 14:58:35|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://[::]:6767|
2025-09-04 14:58:35|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-09-04 14:58:50|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-09-04 16:51:22|ERROR   |root                            |BAZARR Error trying to get rootfolder from Sonarr. Connection Error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 199, in _new_conn\n    sock = connection.create_connection(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/http.py", line 325, in patched_create_connection\n    return _orig_create_connection(address, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 85, in create_connection\n    raise err\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 73, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 789, in urlopen\n    response = self._make_request(\n               ^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 495, in _make_request\n    conn.request(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 441, in request\n    self.endheaders()\n  File "/usr/lib/python3.12/http/client.py", line 1333, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File "/usr/lib/python3.12/http/client.py", line 1093, in _send_output\n    self.send(msg)\n  File "/usr/lib/python3.12/http/client.py", line 1037, in send\n    self.connect()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 279, in connect\n    self.sock = self._new_conn()\n                ^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 214, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffff53f414f0>: Failed to establish a new connection: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 667, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host=\'sonarr\', port=8989): Max retries exceeded with url: /api/v3/rootfolder?apikey=(removed) (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0xffff53f414f0>: Failed to establish a new connection: [Errno 111] Connection refused\'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/rootfolder.py", line 22, in get_sonarr_rootfolder\n    rootfolder = requests.get(url_sonarr_api_rootfolder, timeout=int(settings.sonarr.http_timeout), verify=False, headers=HEADERS)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 73, in get\n    return request("get", url, params=params, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 700, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPConnectionPool(host=\'sonarr\', port=8989): Max retries exceeded with url: /api/v3/rootfolder?apikey=(removed) (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0xffff53f414f0>: Failed to establish a new connection: [Errno 111] Connection refused\'))'|
2025-09-04 16:51:22|ERROR   |root                            |BAZARR Error trying to get tags from Sonarr. Connection Error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 199, in _new_conn\n    sock = connection.create_connection(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/http.py", line 325, in patched_create_connection\n    return _orig_create_connection(address, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 85, in create_connection\n    raise err\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 73, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 789, in urlopen\n    response = self._make_request(\n               ^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 495, in _make_request\n    conn.request(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 441, in request\n    self.endheaders()\n  File "/usr/lib/python3.12/http/client.py", line 1333, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File "/usr/lib/python3.12/http/client.py", line 1093, in _send_output\n    self.send(msg)\n  File "/usr/lib/python3.12/http/client.py", line 1037, in send\n    self.connect()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 279, in connect\n    self.sock = self._new_conn()\n                ^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 214, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffff53f43860>: Failed to establish a new connection: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 667, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host=\'sonarr\', port=8989): Max retries exceeded with url: /api/v3/tag?apikey=(removed) (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0xffff53f43860>: Failed to establish a new connection: [Errno 111] Connection refused\'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 58, in get_tags\n    tagsDict = requests.get(url_sonarr_api_series, timeout=int(settings.sonarr.http_timeout), verify=False, headers=HEADERS)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 73, in get\n    return request("get", url, params=params, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 700, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPConnectionPool(host=\'sonarr\', port=8989): Max retries exceeded with url: /api/v3/tag?apikey=(removed) (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0xffff53f43860>: Failed to establish a new connection: [Errno 111] Connection refused\'))'|
2025-09-04 16:51:22|ERROR   |root                            |BAZARR Error trying to get series from Sonarr. Connection Error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 199, in _new_conn\n    sock = connection.create_connection(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/http.py", line 325, in patched_create_connection\n    return _orig_create_connection(address, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 85, in create_connection\n    raise err\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 73, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 789, in urlopen\n    response = self._make_request(\n               ^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 495, in _make_request\n    conn.request(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 441, in request\n    self.endheaders()\n  File "/usr/lib/python3.12/http/client.py", line 1333, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File "/usr/lib/python3.12/http/client.py", line 1093, in _send_output\n    self.send(msg)\n  File "/usr/lib/python3.12/http/client.py", line 1037, in send\n    self.connect()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 279, in connect\n    self.sock = self._new_conn()\n                ^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 214, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffff53f40710>: Failed to establish a new connection: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 667, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host=\'sonarr\', port=8989): Max retries exceeded with url: /api/v3/series/?apikey=(removed) (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0xffff53f40710>: Failed to establish a new connection: [Errno 111] Connection refused\'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 76, in get_series_from_sonarr_api\n    r = requests.get(url_sonarr_api_series, timeout=int(settings.sonarr.http_timeout), verify=False, headers=HEADERS)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 73, in get\n    return request("get", url, params=params, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 700, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPConnectionPool(host=\'sonarr\', port=8989): Max retries exceeded with url: /api/v3/series/?apikey=(removed) (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0xffff53f40710>: Failed to establish a new connection: [Errno 111] Connection refused\'))'|
2025-09-04 16:51:28|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
2025-09-04 16:57:11|INFO    |root                            |Scheduler will use this timezone: Etc/UTC|
2025-09-04 16:57:13|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-09-04 16:57:13|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-09-04 16:57:13|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-09-04 16:57:13|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://[::]:6767|
2025-09-04 16:57:13|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-09-04 16:57:13|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-09-04 17:04:39|ERROR   |root                            |BAZARR SignalR client for Sonarr connection as been lost. Trying to reconnect...|
2025-09-04 17:04:39|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
2025-09-04 20:06:08|INFO    |root                            |Scheduler will use this timezone: Asia/Jerusalem|
2025-09-04 20:06:09|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-09-04 20:06:09|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-09-04 20:06:09|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-09-04 20:06:09|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://[::]:6767|
2025-09-04 20:06:09|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-09-04 20:06:24|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
