2025-08-29 03:54:36|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
2025-08-29 04:00:00|INFO    |root                            |BAZARR All existing episode subtitles indexed from disk.|
2025-08-29 04:00:00|INFO    |root                            |BAZARR All existing movie subtitles indexed from disk.|
2025-08-29 04:16:06|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2025-08-29 08:56:45|INFO    |root                            |BAZARR Finished searching for Subtitles to upgrade. Check History for more information.|
2025-08-29 09:54:36|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
2025-08-29 10:16:06|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2025-08-29 15:54:36|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
2025-08-29 16:16:06|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2025-08-29 18:55:45|ERROR   |root                            |BAZARR SignalR client for Sonarr connection as been lost. Trying to reconnect...|
2025-08-29 18:55:50|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-08-29 20:56:45|INFO    |root                            |BAZARR Finished searching for Subtitles to upgrade. Check History for more information.|
2025-08-29 21:08:38|INFO    |root                            |BAZARR Running cache maintenance|
2025-08-29 21:54:36|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
2025-08-29 22:16:06|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2025-08-29 23:00:37|ERROR   |root                            |Error trying to get releases from Github. Connection Error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 199, in _new_conn\n    sock = connection.create_connection(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/http.py", line 325, in patched_create_connection\n    return _orig_create_connection(address, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 60, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.12/socket.py", line 978, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsocket.gaierror: [Errno -3] Try again\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 789, in urlopen\n    response = self._make_request(\n               ^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 490, in _make_request\n    raise new_e\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 466, in _make_request\n    self._validate_conn(conn)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 1095, in _validate_conn\n    conn.connect()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 693, in connect\n    self.sock = sock = self._new_conn()\n                       ^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 206, in _new_conn\n    raise NameResolutionError(self.host, self, e) from e\nurllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0xffff73b3fb60>: Failed to resolve \'api.github.com\' ([Errno -3] Try again)\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 667, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff73b3fb60>: Failed to resolve \'api.github.com\' ([Errno -3] Try again)"))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 28, in check_releases\n    r = requests.get(url_releases, allow_redirects=True, timeout=15)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 73, in get\n    return request("get", url, params=params, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 700, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff73b3fb60>: Failed to resolve \'api.github.com\' ([Errno -3] Try again)"))'|
